name: Build-Deploy-Npm
on:
  push:
    branches:
      - 'master'

jobs:
  build-and-push-to-npm:
    name: Bygg og push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@navikt"
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"

      - name: Installer dependencies
        run: |
          yarn
          yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

     - name: "Login to GitHub Docker Registry"
        uses: "docker/login-action@v1"
        with:
          "registry": "ghcr.io"
          "username": "${{ github.actor }}"
          "password": "${{ secrets.GITHUB_TOKEN }}"

      - name: Create a .npmrc file for the github package repository
        uses: FerLuisxd/create-npmrc@3
        with:
          org_name: navikt
        env:
          AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Push
        run: |
          yarn deploy-storybook
          npm run publish:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}